### ISSUE TITLE
JIP script throws errors for civilians

### ISSUE THREAD

**Issue by brndd** [dklollol/Olsen-Framework-Arma-3#100]
When playing as a civilian unit, the JIP script will throw an error like so:
![ij5r9r8](https://cloud.githubusercontent.com/assets/5822375/18611120/493d1098-7d39-11e6-9261-20e7541c688b.png)

This seems to be because  /modules/jip/settings.sqf doesn't have logic for civilian units, only blufor, opfor, and independent.

**Comment by BlackHawkPL** [comment]
Thanks for the report, this will be fixed in next version of framework.
For now you can easily fix it in your mission by adding civilian switch case.
