### ISSUE TITLE
Untrack unit broken (in local MP)

### ISSUE THREAD

**Issue by luiz-silveira** [dklollol/Olsen-Framework-Arma-3#114]
Steps to reproduce: Started local MP game with only me as a player and 1 respawn ticket. Executed { player call FNC_UntrackUnit; }; Watched the world burn.

The errors:

`11:16:59 Error in expression <;
_tempText call FNC_DebugMessage;

};

_return>
11:16:59   Error position: <_return>
11:16:59   Error Undefined variable in expression: _return
11:16:59 File E:\My Documents\Arma 3 - Other Profiles\Luiz%20Silveira\mpmissions\CO29_HC_BRA4_Caught_in_the_crossfire_v8_test.Tanoa\core\functions\fnc_getTeamVariable.sqf, line 42
11:16:59 Error in expression <team, 4] call FNC_GetTeamVariable;

if (_start == 0) then {

private _tempText =>
11:16:59   Error position: <_start == 0) then {

private _tempText =>
11:16:59   Error Undefined variable in expression: _start
11:16:59 File E:\My Documents\Arma 3 - Other Profiles\Luiz%20Silveira\mpmissions\CO29_HC_BRA4_Caught_in_the_crossfire_v8_test.Tanoa\core\functions\fnc_casualtyPercentage.sqf, line 22`

**Comment by BlackHawkPL** [comment]
#166
