### ISSUE TITLE
Suggestion: ACRE Scramble turned off in spectator

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#151]
We should add a check for FW_enable_babel = true, in our spectator script and if its true then add all FW_all_languages to the user that entered spectator.

This would allow dead players to understand players that are still alive from both sides.

example: https://clips.twitch.tv/SteamySquareWalletDBstyle

**Comment by Nathan423** [comment]
A possible fix is located [here](https://github.com/dklollol/Olsen-Framework-Arma-3/pull/159/commits/b3912f92a8ae658e9cb0d01aafa6205819637762)

**Comment by BlackHawkPL** [comment]
#166
