### ISSUE TITLE
guerilla mispelled in core/init.sqf

### ISSUE THREAD

**Issue by Drofseh** [dklollol/Olsen-Framework-Arma-3#152]
Version 3.3.1

https://github.com/dklollol/Olsen-Framework-Arma-3/blob/master/core/init.sqf#L36

`"guerrila" call FNC_CreateRespawnMarker;`

Is `guerrila` an intentional mispelling?
Correct spelling should be `guerilla`.

**Comment by BlackHawkPL** [comment]
#156
