### ISSUE TITLE
Ai Drivers

### ISSUE THREAD

**Issue by k1ngb34v3r** [dklollol/Olsen-Framework-Arma-3#158]
Unable to spawn an Ai driver in Eden with the latest version.

**Comment by BlackHawkPL** [comment]
I will need more information.
By 'in Eden' you mean while previewing mission?
Do you have the option in interaction menu? (that's where it is now)

**Comment by k1ngb34v3r** [comment]
I managed to fix it. It seems that changing the variable name of the vehicle by a letter and deleting and then copy/pasting the ai_drivers file about ten times managed to fix it.

**Comment by BlackHawkPL** [comment]
Good to hear, closing.
