### ISSUE TITLE
Improvement: module jip_teleport

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#25]
I think it would improve the module if Jip Teleport would not be able to be used if there is enemies within x meters of the SL.

This is mostly a problem when playing TVT.

**Comment by k1ngb34v3r** [comment]
This is dumb for TVTs. JIPs for defenders generally don't have to teleport or very far. If you take away the ability for attacking JIPs to join their teams then the attack can become very imbalanced in favor of the defenders.

**Comment by Starfox64** [comment]
Feature won't be implemented.
