### ISSUE TITLE
request: module parameters.

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#26]
I would love to see a module that gives me the abbility to add parameters to the mission.

examples:

Time of day.
(dawn, early morning, morning, noon, afternoon, evening, dusk, night)

Weather:
clear (calm), clear (light winds), clear (strong winds), overcast (calm), overcast (light winds), overcast (strong winds), rain (calm), rain (light winds), rain (strong winds)

Fog:
None, light, Heavy

**Comment by Starfox64** [comment]
Working on it.

**Comment by Starfox64** [comment]
**Added the env_parameters module** https://github.com/dklollol/Olsen-Framework-Arma-3/commit/970c1e09242340a9d6795c81cdd59d37f89c6ae4
The module adds basic weather and time parameters, I won't be making a 'framework' for the parameters system of ArmA 3 is it would be just re-inventing the wheel, however you can add your own parameters to _params.hpp_, for more information on how to user parameters read this https://community.bistudio.com/wiki/Arma_3_Mission_Parameters

Closing #19.

**Comment by dklollol** [comment]
The current setup of the framework allows modules to individually declare parameters using this in the root.sqf

#ifdef description_params

	#include "params.sqf"

#endif

**Comment by dklollol** [comment]
reopen so that you all notice
