### ISSUE TITLE
Easy Gear Export

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#28]
I would like to request something like what was in the framework for A2, where you could gear up your guy, and then run into a trigger, and it would export all gear to rpt file.

If it could add the ["EXPORTED_CLASSNAME_HERE", amount, place] call FNC_AddItem;" then that would just be icing on the cake :)

**Comment by Starfox64** [comment]
**Feature Added**
https://github.com/dklollol/Olsen-Framework-Arma-3/commit/fb1d0ad6e5269a80704d8fdfe8ba6c75fdc5fef6
