### ISSUE TITLE
Set radio channel doesnt seem to work

### ISSUE THREAD

**Issue by moonmanmove** [dklollol/Olsen-Framework-Arma-3#32]
as the title says, i've tried using the set radio channel module, and it does not work.

**Comment by Reyfin** [comment]
Need more Information because it works on my end.
Is the module enabled in Modules.sqf?
How do you call the FNC?

**Comment by Starfox64** [comment]
@moonmanmove Please give us more information, if this issue hasn't been updated within 48 hours it will be closed.

**Comment by moonmanmove** [comment]
my mistake, did not enable the module. Once again, sorry.
