### ISSUE TITLE
Zeus + Acre + AI control

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#33]
I have been searching the big interwebs but was not able to see if this is even duable. So i guess i should just ask you guys if you think it can be done.

As Zeus when you take control of an AI, if you now try to talk using acre radio/direct the volume is not comming out of the controlled AI, but out of the Zeus unit. (the players unit)

Is there a way to set an AI as the output for acre, and also be able to hear other players from that unit.

**Comment by Starfox64** [comment]
Please contact the ACRE2 team about this.
