### ISSUE TITLE
start_on_radio_channel - Updated for 343 Blocks

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#35]
Hi, 

I would love if someone who knew what they are doing could update the start_on_radio_channel module to allow preset 343´s on different blocks.

Thanks :)

**Comment by Starfox64** [comment]
On the 343 blocks are not an additional variable, to switch to the next block you simply keep incrementing the channel number past it's "maximum" meaning that to set a 343 to Channel 1 Block 2 you set the channel to 17.
For Channel 1 Block 3 you set it to 33.

**Comment by perfk** [comment]
Oh, awesome.
Could this info be added to the module settings file?
