### ISSUE TITLE
start_on_radio_channel - Respawn

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#36]
Hi,

I'm looking for a way to keep the player on the channel that i'm setting them on when they respawn.

Unless you guys can think of something clever, do i think my only option would be to name all units, and then do something like the gearscript, where it looks trough the name, and assigns radio channels from that..... but really hopeing, for you guys to cook something clever togeather. as my solution feels really slow, and tiresome to setup.

**Comment by perfk** [comment]
I think he most important would be to set the 343´s as, most who will be given a long range, should be able to set their radios correctly, but umm, yeah.. not everyone with a 343 knows how to do basic stuff. and thats okay, thats why we do this, to try and help them.

Could we use the 1'1 in =  [this, "RIFLE", "1'1"] call FNC_GearScript; and send that to the start_on_radio_channel  settings file?. so we could set everyone who has the 1'1 to channel X, and everyone that is 1'2 to X and so on.

**Comment by dklollol** [comment]
The module now sets the channel when ever a radio is spawned.

They way ACRE works is that you spawn a base radio without an id.
Then it gets an id, and thats where the module goes and looks if this radio is given to a player with a preset for it and then sets it to that.

So now channels are set on respawn.
