### ISSUE TITLE
Feature Request: (Module: env_parameters) add in options for date and time limit.

### ISSUE THREAD

**Issue by Morluck** [dklollol/Olsen-Framework-Arma-3#41]
examples: 
date - (day) / (month) / (year-optional)
time limit- (Default) / (+15 Minute) / (+30 minute)
 shown as- (30 Min) / (45 Min) / (60 Min)

**Comment by dklollol** [comment]
Added the ability to change the time limit and default optionsx for all fields.

But i didn't add the ability to change the date. Make a new request for date and argue the case, i think mission makers wouldn't want you to set the DDAY invasion to 24 December 2016
