### ISSUE TITLE
Mission doesn't end with latest spec

### ISSUE THREAD

**Issue by k1ngb34v3r** [dklollol/Olsen-Framework-Arma-3#45]
When the end conditions are meet the screen goes to the end screen with the casualty percentages but does not kick back to the mission list screen. It just sits there indefinitely or a really long time that is unacceptable. I have to press esc twice; the first time kicks me back to the mission where I can spectate normally, and the second time finally pushes the server to the mission list screen.

**Comment by k1ngb34v3r** [comment]
Also, why does the spec center on the map rather than starting on where the player died?

**Comment by perfk** [comment]
This is not something that i have encountered, If its still a issue would i not mind taking a look at your mission :)

**Comment by k1ngb34v3r** [comment]
It is the most recent OFW Voiper spec that I was having trouble with. GDT works fine.

**Comment by perfk** [comment]
I have now tested and can confirm. - The module is conflicting with how the framework ends the mission, so you have to press Escape twice to get out.

Using the standard Olsen Spectator works fine.

**Comment by Reyfin** [comment]
Was a bug in the spectator.
