### ISSUE TITLE
End Conditions being checked while in the briefing before starting mission

### ISSUE THREAD

**Issue by Davidj361** [dklollol/Olsen-Framework-Arma-3#46]
For the file, customization/EndConditions.sqf
The end conditions are being checked while in the briefing. I ran into a bug where the mouse was clicking very rapid and I could not exit the brief in any matter what so ever. This happened because the mission was ending in the brief. I fixed it with surrounded the end conditions with if (time > 1) then { // end conditions }; in your customization/EndConditions.sqf
You might want to add that to your master branch as in my opinion end conditions should not be checked while in the briefing.

**Comment by Reyfin** [comment]
With it being checked though you will never brief for a mission which would end instantly.

**Comment by Davidj361** [comment]
It does not hurt to make it failsafe.

**Comment by Reyfin** [comment]
closing due age/ not really sure if its a real bug / and if people don't want them checked they can add it themselves.
