### ISSUE TITLE
The hostage module doesn't work in multiplayer

### ISSUE THREAD

**Issue by Davidj361** [dklollol/Olsen-Framework-Arma-3#48]
When you try to free a hostage in multiplayer, the hostage stays sitting down down and cuffed. It works in single player though.

**Comment by Davidj361** [comment]
I fixed it with these changes:
    if (hasInterface) then {
        _unit addAction ["<t color='#FBB829'>Rescue Hostage</t>",{
            [-2,{_this call FNC_RescueHostage;},[_this select 0, _this select 1]] call CBA_fnc_globalExecute;
        }, nil, 6, true, true, "", "(_target distance _this) < 2 && !(_target getVariable ['FW_Rescued', false]);"];
    };

    // Have to search part of the string as the animation differs
    if (animationState _unit find "acts_aidlpsitmstpssurwnondnon" != -1) then {

**Comment by Reyfin** [comment]
Fixed closing
