### ISSUE TITLE
JIP Deny Not Working Properly

### ISSUE THREAD

**Issue by k1ngb34v3r** [dklollol/Olsen-Framework-Arma-3#49]
I noticed that on two missions that prevent JIPs after 5 minutes, players are still able to join after the timer has expired.

Noted on: 

TVT66 The Green Zone v1.2
http://aar.unitedoperations.net//replay/7E4C764E99805E39E27C522C39A0E148

and

TVT46 Sobor Assault v1
http://aar.unitedoperations.net//replay/19969F4D2667C7F91B321D92C3324E82

**Comment by Reyfin** [comment]
Not really sure why this happend in those missions. Just tested it and it works fine.

**Comment by Starfox64** [comment]
I would be great if anyone could confirm this in a mission of their own. I'll keep this issue open for a week or two, if there is still no feedback by then, it will be closed. Feel free to re-open it if it turns out JIP_DENY is actually broken.
