### ISSUE TITLE
End Condition - Move timelimit into EndConditon

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#57]
Olsen-Framework-Arma-3/customization/settings.sqf

FW_TimeLimit = 30; //Time limit in minutes, to disable the time limit set it to 0 should be moved into Olsen-Framework-Arma-3/customization/endConditions.sqf as people have a tendency to try and edit 
`if ((time / 60) >= FW_TimeLimit && FW_TimeLimit != 0) exitWith {`
This is prone to errors. where i think it might be better to just move FW_TimeLimit = 30;  straight into endConditions.sqf

**Comment by dklollol** [comment]
Moved the time limit into the init.sqf

This means the code for the time limit will always be there for all missions. Just use FW_TimeLimit = 0 to disable or use it.
