### ISSUE TITLE
[Feature] - Endscreen showing Your Kills

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#60]
Default arma endscreen: http://i.imgur.com/c7LMbsT.jpg

Something like it should be a part of the Framework Endscreen.

It should show:
- Total amount killed
- Amount killed from each opposing Team (framework team)
  -- If less than 10, Show names. (for AI and Players)

If you died, let the player know who killed him.
Killer: Perfk
Friendly Fired by: Perfk
- I'm not 100% if this is something we want to show the players, as it could end up like any other FPS, where its about how many kills you get, and not how it should be: How you did as a team.

Suggestions are welcome :)

**Comment by luiz-silveira** [comment]
I wouldn't show this to players. It's only one more incentive for players to go for nothing but kills instead of going for team cooperation, especially on TVTs.

**Comment by BlackHawkPL** [comment]
Currently unfeasible due to ACE medical killing people, making half of deaths have no killer info. Maybe this will be worth looking into after ACE medical rewrite.

**Comment by BlackHawkPL** [comment]
Somewhat done with ACEX tab thing. #156
