### ISSUE TITLE
Potential counting bug

### ISSUE THREAD

**Issue by dklollol** [dklollol/Olsen-Framework-Arma-3#61]
While testing my mission Perfk glitched his landrover into mine and Blackhawks using the setup timer's ao limit feature causing a massive explosion and killing blackhawk twice which counted double.

**Comment by Starfox64** [comment]
By that you mean that the Eh was called twice in a row or that blackhawk legitimately died twice?

**Comment by dklollol** [comment]
EH was called twice.

**Comment by BlackHawkPL** [comment]
Killed EH now won't fire if unit is dead, should fix this issue if BI hasn't fixed double-firing EHs already.
