### ISSUE TITLE
Proper Cleanup script

### ISSUE THREAD

**Issue by perfk** [dklollol/Olsen-Framework-Arma-3#66]
Olsen please look into creating a cleanup script cable of at least the following but with parameters for ecah.

Remove dead bodies.
Remove items on the ground
remove destroyed vehicles
remove disabled vehicles

config.
only remove if no player is withing x meter.
Dont remove everything at the same time, do something like. Check for _x to delete, and then add a timer to _x and remove it after y time.

**Comment by BlackHawkPL** [comment]
IMHO there's enough mess already with only vanilla GC....
Let's not reinvent the wheel.
