### ISSUE TITLE
Choice of "random" in mission params

### ISSUE THREAD

**Issue by luiz-silveira** [dklollol/Olsen-Framework-Arma-3#91]
I'd be good to have an option in the params to let the server decide which of the options to set it to. So not completely random, but a random selection from within the given array.

So if `values[] = {-1, 7, 12, 15, 17};`, it's be nice to another option to let the server randomly set one of those 5.

--------------------

As a very side note and it probably doesn't belong here: Is there a way to set the time of day not to full hours? I'd love to set it to `values[] = {-1, 7.5, 12, 15, 17.2};` etc., or any other way to control minutes too.

Thanks!

**Comment by BlackHawkPL** [comment]
fixed in #105
